from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from google.adk.sessions import InMemorySessionService
import uuid
from srs_engine.agents.introduction_agent import create_introduction_agent 
from srs_engine.agents.overall_description_agent import create_overall_description_agent 
from srs_engine.agents.system_features_agent import create_system_features_agent
from srs_engine.agents.external_interfaces_agent import create_external_interfaces_agent
from srs_engine.agents.nfr_agent import create_nfr_agent
from srs_engine.agents.glossary_agent import create_glossary_agent
from srs_engine.agents.assumptions_agent import create_assumptions_agent
from srs_engine.schemas.srs_input_schema import SRSRequest
from srs_engine.utils.globals import (
    create_session , 
    create_runner , 
    create_prompt , 
    generated_response , 
    get_session , 
    clean_and_parse_json,
    clean_interface_diagrams,
    render_mermaid_png)
from google.adk.agents import SequentialAgent , ParallelAgent
from pathlib import Path
import time
from datetime import datetime
from srs_engine.utils.srs_document_generator import generate_srs_document

today = datetime.today().strftime("%m/%d/%Y")

app = FastAPI()

app.mount(
    "/static",
    StaticFiles(directory="srs_engine/static"),
    name="static"
)


templates = Jinja2Templates(directory="srs_engine/templates")

session_service_stateful = InMemorySessionService()


async def create_srs_agent():
     
    first_agent = SequentialAgent(
          name = "first_agent",
          sub_agents = [
               ParallelAgent(
                    name = "first_parallel_agent",
                    sub_agents = [
                         create_introduction_agent(),
                         create_overall_description_agent(),
                         create_system_features_agent(),
                         create_external_interfaces_agent(),
                         create_nfr_agent()
                    ],
                    description = "This agent handles the generation of the Introduction and Overall Description sections of the SRS document."
               )
          ]
     )

    second_agent = SequentialAgent(
          name = "second_agent",
          sub_agents = [
               ParallelAgent(
                   name = "finalization_agent",
                   sub_agents = [
                       create_glossary_agent(),
                       create_assumptions_agent()
                   ],
                   description = "This agent handles the generation of the Glossary and Assumptions sections of the SRS document."
               )
          ]
     )

    
    return first_agent , second_agent











@app.get("/", response_class=HTMLResponse)
async def root(request: Request):
    return templates.TemplateResponse(
        "home.html",
        {"request": request}
    )


@app.post("/generate_srs")
async def generate_srs(srs_data: SRSRequest):


    print("Received SRS Data: ", srs_data)
    session_id = str(uuid.uuid4())

    inputs = srs_data.dict()
    project_name = inputs["project_identity"]["project_name"] # will be used later
    author_list = inputs["project_identity"]["author"] # will be used later
    organization_name = inputs["project_identity"]["organization"] # will be used later

    user_id = "test"  # In real scenarios, fetch from auth system

    initial_state = { "user_inputs": inputs }

    print(f'''Project Name: {project_name}''')
    print(f'''Authors: {author_list}''')
    print(f'''Organization: {organization_name}''')
    print(f'Initial state: {initial_state}')

    await create_session(session_service_stateful, project_name, user_id, session_id , initial_state)


    print("Session created with ID: ", session_id)

    first_agent , second_agent  = await create_srs_agent()
    runner = await create_runner(first_agent, project_name, session_service_stateful)

    print("Runner created for agent ")
    prompt = await create_prompt()

    print("Prompt created for agent ")

    response = await generated_response(runner , user_id , session_id , prompt)

    print("Response generated by agent ")

    session = await get_session(session_service_stateful,project_name , user_id , session_id)

    print("Session state after agent run: ", session.state)

    
    time.sleep(20) 


    second_runner = await create_runner(second_agent, project_name, session_service_stateful)   
    
    print(f"Second Runner created for agent ")

    second_response = await generated_response(second_runner , user_id , session_id , prompt)

    print("Response generated by second agent ")

    session = await get_session(session_service_stateful,project_name , user_id , session_id)

    print("Session state after second agent run: ", session.state)
    

    introduction_section = clean_and_parse_json(session.state.get("introduction_section", {}))
    print("Introduction Section: ", introduction_section)
    overall_description_section = clean_and_parse_json(session.state.get("overall_description_section", {}))
    print("Overall Description Section: ", overall_description_section)
    system_features_section = clean_and_parse_json(session.state.get("system_features_section", {}))
    print("System Features Section: ", system_features_section)
    external_interfaces_section = clean_interface_diagrams(clean_and_parse_json(session.state.get("external_interfaces_section", {})))
    print("External Interfaces Section: ", external_interfaces_section)


    image_paths = {
    'user_interfaces': Path(f'./srs_engine/static/{project_name}_user_interfaces_diagram.png'),
    'hardware_interfaces': Path(f'./srs_engine/static/{project_name}_hardware_interfaces_diagram.png'),
    'software_interfaces': Path(f'./srs_engine/static/{project_name}_software_interfaces_diagram.png'),
    'communication_interfaces': Path(f'./srs_engine/static/{project_name}_communication_interfaces_diagram.png')
}


    render_mermaid_png(external_interfaces_section['user_interfaces']['interface_diagram']['code'], image_paths['user_interfaces'])
    render_mermaid_png(external_interfaces_section['hardware_interfaces']['interface_diagram']['code'], image_paths['hardware_interfaces'])
    render_mermaid_png(external_interfaces_section['software_interfaces']['interface_diagram']['code'], image_paths['software_interfaces'])
    render_mermaid_png(external_interfaces_section['communication_interfaces']['interface_diagram']['code'], image_paths['communication_interfaces'])




    nfr_section = clean_and_parse_json(session.state.get("nfr_section", {}))
    print("Non-Functional Requirements Section: ", nfr_section)


    glossary_section = clean_and_parse_json(session.state.get("glossary_section", {}))
    print("Glossary Section: ", glossary_section)


    assumptions_section = clean_and_parse_json(session.state.get("assumptions_section", {}))
    print("Assumptions Section: ", assumptions_section)


    ## SRS Making ##
    output_path = f"./srs_engine/generated_srs/{project_name}_SRS.docx"

    Path("./srs_engine/generated_srs").mkdir(exist_ok=True)

    generated_path = generate_srs_document(
        project_name=project_name,
        introduction_section=introduction_section,
        overall_description_section=overall_description_section,
        system_features_section=system_features_section,
        external_interfaces_section=external_interfaces_section,
        nfr_section=nfr_section,
        glossary_section=glossary_section,
        assumptions_section=assumptions_section,
        image_paths=image_paths,
        output_path=output_path,
        authors=author_list , # List of authors
        organization=organization_name
    )

    print(f"✅ SRS document generated successfully: {generated_path}")




    return {
        "srs_document_path": generated_path
    }













