from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from google.adk.sessions import InMemorySessionService
import uuid
from srs_engine.agents.introduction_agent import create_introduction_agent , introduction_agent
from srs_engine.agents.overall_description_agent import create_overall_description_agent , overall_description_agent
from srs_engine.schemas.srs_input_schema import SRSRequest
from srs_engine.utils.globals import create_session , create_runner , create_prompt , generated_response , get_session , clean_and_parse_json
from google.adk.agents import SequentialAgent , ParallelAgent

app = FastAPI()

app.mount(
    "/static",
    StaticFiles(directory="srs_engine/static"),
    name="static"
)


templates = Jinja2Templates(directory="srs_engine/templates")

session_service_stateful = InMemorySessionService()


async def create_srs_agent():
     
     srs_agent = SequentialAgent(
          name = "srs_agent",
          sub_agents = [
               ParallelAgent(
                    name = "parallel_agent",
                    sub_agents = [
                         create_introduction_agent(),
                         create_overall_description_agent()
                    ],
                    description = "This agent handles the generation of the Introduction and Overall Description sections of the SRS document."
               )
          ]
     )

     return srs_agent



@app.get("/", response_class=HTMLResponse)
async def root(request: Request):
    return templates.TemplateResponse(
        "home.html",
        {"request": request}
    )


@app.post("/generate_srs")
async def generate_srs(srs_data: SRSRequest):

    
    print("Received SRS Data: ", srs_data)
    session_id = str(uuid.uuid4())

    inputs = srs_data.dict()
    project_name = inputs["project_identity"]["project_name"] # will be used later
    author_list = inputs["project_identity"]["author"] # will be used later
    organization_name = inputs["project_identity"]["organization"] # will be used later

    user_id = "test"  # In real scenarios, fetch from auth system

    initial_state = { "user_inputs": inputs }

    print(f'''Project Name: {project_name}''')
    print(f'''Authors: {author_list}''')
    print(f'''Organization: {organization_name}''')
    print(f'Initial state: {initial_state}')

    await create_session(session_service_stateful, project_name, user_id, session_id , initial_state)


    print("Session created with ID: ", session_id)

    srs_agent = await create_srs_agent()
    runner = await create_runner(srs_agent, project_name, session_service_stateful)

    print("Runner created for agent ")
    prompt = await create_prompt()

    print("Prompt created for agent ")

    response = await generated_response(runner , user_id , session_id , prompt)

    print("Response generated by agent ")

    session = await get_session(session_service_stateful,project_name , user_id , session_id)

    print("Session state after agent run: ", session.state)

    introduction_section = clean_and_parse_json(session.state.get("introduction_section", {}))
    print("Introduction Section: ", introduction_section)
    overall_description_section = clean_and_parse_json(session.state.get("overall_description_section", {}))
    print("Overall Description Section: ", overall_description_section)

    return {
        "introduction_section": introduction_section,
        "overall_description_section": overall_description_section,
        "full_response": response
    }













